export const SET_LOADING = "SET_LOADING";

export const MODE = {
  SET_UPDATE: "SET_UPDATE",
  SET_CREATE: "SET_CREATE",
  SET_CLEAR_STATUS: "SET_CLEAR_STATUS",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_CLEAR_ERROR_MESSAGE: "SET_CLEAR_ERROR_MESSAGE",
};

export const LOGIN = {
  SET_LOGIN: "SET_LOGIN",
  SET_LOGOUT: "SET_LOGOUT",
  SET_ACOUNT: "SET_ACOUNT",
  SET_OTP: "SET_OTP",
  SET_EMAIL: "SET_EMAIL",
  SET_CLEAR_OTP: "SET_CLEAR_OTP",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_CLEAR_ERROR_MESSAGE: "SET_CLEAR_ERROR_MESSAGE",
};

export const ACCOUNT = {
  SET_ACCOUNT: "SET_ACCOUNT",
  SET_ACCOUNTS: "SET_ACCOUNTS",
  SET_ERROR_STATUS: "SET_ERROR_STATUS",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_CLEAR_ERROR_MESSAGE: "SET_CLEAR_ERROR_MESSAGE",
};

export const PERMISSION = {
  SET_PERMISSION: "SET_PERMISSION",
  SET_PERMISSIONS: "SET_PERMISSIONS",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_CLEAR_ERROR_MESSAGE: "SET_CLEAR_ERROR_MESSAGE",
};

export const TRAINING = {
  SET_LIST_TRAINING_PROGRAM: "SET_LIST_TRAINING_PROGRAM",
  SET_TRAINING_PROGRAM_DETAIL: "SET_TRAINING_PROGRAM_DETAIL",
  SAVE_TP_NAME: "SAVE_TP_NAME",
  IMPORT_TP: "IMPORT_TP",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_CLEAR_ERROR_MESSAGE: "SET_CLEAR_ERROR_MESSAGE",
};

export const MATERIAL = {
  UPLOAD_MATERIAL: "UPLOAD_MATERIAL",
  DELETE_MATERIAL: "DELETE_MATERIAL",
  GET_MATERIAL: "GET_MATERIAL",
  SET_MATERIAL: "SET_MATERIAL",
  SET_MATERIALS: "SET_MATERIALS",
  SET_FILES: "SET_FILES",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_CLEAR_ERROR_MESSAGE: "SET_CLEAR_ERROR_MESSAGE",
};

export const SYLLABUS = {
  SAVE_AS_DRAFT: "SAVE_AS_DRAFT",
  SAVE: "SAVE",
  CANCEL: "CANCEL",
  SET_DRAFT: "SET_DRAFT",
  SET_LEVEL: "SET_LEVEL",
  SET_DELIVERY: "SET_DELIVERY",
  SET_OUTPUT_STANDARD: "SET_OUTPUT_STANDARD",
  SET_LIST_SYLLABUS: "SET_LIST_SYLLABUS",
  GET_LIST_SYLLABUS_BY_SEARCH: "GET_LIST_SYLLABUS_BY_SEARCH",
  GET_LIST_SYLLABUS_BY_DATE: "GET_LIST_SYLLABUS_BY_DATE",
  DUPLICATE_SYLLABUS: "DUPLICATE_SYLLABUS",
  SORT_SYLLABUS: "SORT_SYLLABUS",
  DELETE_SYLLABUS: "DELETE_SYLLABUS",
  GET_SYLLABUS_ITEM: "GET_SYLLABUS_ITEM",
};

export const PROGRAM_SYLLABUS = {
  SET_SYLLABUS: "SET_SYLLABUS",
  SET_SYLLABUSES: "SET_SYLLABUSES",
  ADD_SYLLABUS_FOR_TP: "ADD_SYLLABUS_FOR_TP",
  DELETE_SYLLABUS_FOR_TP: "DELETE_SYLLABUS_FOR_TP",
  UPDATE_LIST_SYLLABUS_CHOOSE: "UPDATE_LIST_SYLLABUS_CHOOSE", //truyen 1 mang vao
  SET_PROGRAM_SYLLABUS_DETAIL: "SET_PROGRAM_SYLLABUS_DETAIL",
  SET_PROGRAM_SYLLABUS_TO_EDIT: "SET_PROGRAM_SYLLABUS_TO_EDIT",
  SET_PROGRAM_TO_EDIT_IN_LIST: "SET_PROGRAM_TO_EDIT_IN_LIST",
  SET_PROGRAM_SYLLABUS_TO_SAVE_COMPLETE:
    "SET_PROGRAM_SYLLABUS_TO_SAVE_COMPLETE",
  CLEAR_PROGRAM_SYLLABUS_TO_SAVE_COMPLETE:
    "CLEAR_PROGRAM_SYLLABUS_TO_SAVE_COMPLETE",
  SET_LIST_PROGRAM_SYLLABUS_DRAFT: "SET_LIST_PROGRAM_SYLLABUS_DRAFT",
  SET_LIST_PROGRAM_SYLLABUS_COMPLETE: "SET_LIST_PROGRAM_SYLLABUS_COMPLETE",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_CLEAR_ERROR_MESSAGE: "SET_CLEAR_ERROR_MESSAGE",
};

export const SYLLABUS_DETAIL = {
  GET_SYLLABUS_DETAIL_BY_ID: "GET_SYLLABUS_DETAIL_BY_ID",
};

export const CREATE_TP = {
  CREATE_TP_NAME: "CREATE_TP_NAME",
  ADD_SYLLABUS_FOR_TP: "ADD_SYLLABUS_FOR_TP",
  DELETE_SYLLABUS_FOR_TP: "DELETE_SYLLABUS_FOR_TP",
  UPDATE_LIST_SYLLABUS_CHOOSE: "UPDATE_LIST_SYLLABUS_CHOOSE", //truyen 1 mang vao
  SAVE_LIST_SYLLABUS_CHOOSE: "SAVE_LIST_SYLLABUS_CHOOSE", //truyen 1 mang vao
};

export const CALENDAR = {
  SET_CLASS_LOCATION: "SET_CLASS_LOCATION",
  SET_CLASS_STATUS: "SET_CLASS_STATUS",
  SET_CLASS_ATTENDEE: "SET_CLASS_ATTENDEE",
  SET_CLASS_FSU: "SET_CLASS_FSU",
  SET_CLASS_FORMAT_TYPE: "SET_CLASS_FORMAT_TYPE",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  SET_CLEAR_ERROR_MESSAGE: "SET_CLEAR_ERROR_MESSAGE",
};
